# Generated by Django 4.2.6 on 2023-10-29 11:36
import json
import os
from django.db import migrations

def populate_data(apps, schema_editor):
    MyModel = apps.get_model('posts', 'Tag')
    fixture_path = os.path.join(os.path.dirname(__file__), 'fixtures/fixture.json')
    with open(fixture_path) as f:
        tag = json.load(f)
    for i in tag:
        instance = MyModel(name=tag[i])
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag_posts_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='author',
        ),
        migrations.RunPython(populate_data)
    ]
