# Generated by Django 4.2.6 on 2023-10-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag_posts_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='author',
        ),
    ]
